import type { WorkoutDisplay } from "./types";

const IMAGE_BASE = "https://rabudzkpputmollmpodd.supabase.co/storage/v1/object/public/exercise-images";
const exerciseImage = (path: string) => `${IMAGE_BASE}/${path}/0.jpg`;

export const mockWorkout: WorkoutDisplay = {
  id: "demo-boxing-engine",
  title: "Boxing Engine: Legs, Core and Shoulder Armour",
  goal: "Build a repeatable conditioning base that carries into longer boxing rounds without turning the session into random gym punishment.",
  durationMinutes: 42,
  difficulty: "Intermediate",
  equipment: ["Dumbbells", "Resistance band", "Skipping rope", "Bodyweight"],
  visibility: "private",
  intakeSummary:
    "Generated from an intake asking for boxing-specific conditioning, shoulder resilience, explosive legs and enough core work to keep shape under fatigue.",
  createdAt: new Date("2026-05-05T06:00:00.000Z").toISOString(),
  sections: [
    {
      type: "warmup",
      title: "Warm up the engine",
      eyebrow: "Warmup",
      description: "Raise temperature, open the hips and switch on rotation before the harder work starts.",
      items: [
        {
          id: "mock-skip",
          orderIndex: 1,
          blockType: "warmup",
          blockTitle: "Warm up the engine",
          exercise: {
            id: "jump-rope",
            name: "Battling Ropes",
            category: "conditioning",
            imageUrl: exerciseImage("Battling_Ropes"),
            equipment: ["Skipping rope"],
            instructions: ["Alternately raise and lower each rope in a wave pattern.", "Keep your trunk braced and rhythm consistent."],
          },
          sets: 3,
          reps: null,
          durationSeconds: 60,
          restSeconds: 20,
          tempo: "Easy bounce",
          coachingNote: "Use this as a hard conditioning primer without losing posture.",
          coachingCues: ["Tall posture", "Quiet feet", "Breathe through the nose where possible"],
          boxingRelevance: "Shoulder endurance and trunk stiffness carry directly into late-round output.",
        },
        {
          id: "mock-worlds-greatest",
          orderIndex: 2,
          blockType: "warmup",
          blockTitle: "Warm up the engine",
          exercise: {
            id: "worlds-greatest-stretch",
            name: "All Fours Quad Stretch",
            category: "mobility",
            imageUrl: exerciseImage("All_Fours_Quad_Stretch"),
            equipment: ["Bodyweight"],
            instructions: ["Start on all fours and draw one heel towards your glutes.", "Keep the hips controlled while you open the front of the thigh."],
          },
          sets: 2,
          reps: "5 each side",
          durationSeconds: null,
          restSeconds: 15,
          tempo: "Controlled",
          coachingNote: "Keep this controlled. The goal is range, not theatrics.",
          coachingCues: ["Long spine", "Front foot rooted", "Rotate from ribs"],
          boxingRelevance: "Looser quads and hips make stance, footwork and knee bend easier to keep.",
        },
      ],
    },
    {
      type: "main",
      title: "Strength circuit",
      eyebrow: "Main work",
      description: "Alternating legs, pull and trunk so the session builds boxing durability without frying one joint pattern.",
      items: [
        {
          id: "mock-goblet-squat",
          orderIndex: 3,
          blockType: "main",
          blockTitle: "Strength circuit",
          exercise: {
            id: "goblet-squat",
            name: "Bodyweight Squat",
            category: "strength",
            imageUrl: exerciseImage("Bodyweight_Squat"),
            equipment: ["Dumbbell"],
            instructions: ["Stand tall, feet around shoulder width.", "Sit the hips back and down, then stand with control."],
          },
          sets: 4,
          reps: "8-10",
          durationSeconds: null,
          restSeconds: 45,
          tempo: "3-1-1",
          coachingNote: "Keep the reps crisp and balanced. Do not chase fatigue with ugly squats.",
          coachingCues: ["Tripod foot", "Knees track toes", "Ribs stacked over pelvis"],
          boxingRelevance: "Clean squatting builds the leg base for stance, balance and repeat efforts.",
        },
        {
          id: "mock-band-row",
          orderIndex: 4,
          blockType: "main",
          blockTitle: "Strength circuit",
          exercise: {
            id: "band-row",
            name: "Alternating Renegade Row",
            category: "strength",
            imageUrl: exerciseImage("Alternating_Renegade_Row"),
            equipment: ["Resistance band"],
            instructions: ["Set up in a strong plank position with dumbbells or hands planted.", "Row one side at a time while keeping the hips quiet."],
          },
          sets: 4,
          reps: "12-15",
          durationSeconds: null,
          restSeconds: 30,
          tempo: "2-1-2",
          coachingNote: "Move slowly enough that your hips do not twist all over the place.",
          coachingCues: ["Neck long", "Elbows finish behind ribs", "No shrugging"],
          boxingRelevance: "Anti-rotation and upper-back strength help you keep posture when punching under fatigue.",
        },
        {
          id: "mock-deadbug",
          orderIndex: 5,
          blockType: "main",
          blockTitle: "Strength circuit",
          exercise: {
            id: "dead-bug",
            name: "Dead Bug",
            category: "core",
            imageUrl: exerciseImage("Dead_Bug"),
            equipment: ["Bodyweight"],
            instructions: ["Press lower back gently into the floor.", "Reach opposite arm and leg without ribs flaring."],
          },
          sets: 4,
          reps: "8 each side",
          durationSeconds: null,
          restSeconds: 30,
          tempo: "Slow",
          coachingNote: "If your back arches, the rep does not count. Tragic, but fair.",
          coachingCues: ["Exhale hard", "Ribs down", "Move slow enough to own it"],
          boxingRelevance: "Anti-extension control protects shape when punching, slipping and bracing under fatigue.",
        },
      ],
    },
    {
      type: "finisher",
      title: "Round five finisher",
      eyebrow: "Finisher",
      description: "A short punchy close that feels like late-round pressure without needing a heavy bag.",
      items: [
        {
          id: "mock-shadow-sprint",
          orderIndex: 6,
          blockType: "finisher",
          blockTitle: "Round five finisher",
          exercise: {
            id: "shadowboxing-sprint",
            name: "Mountain Climbers",
            category: "conditioning",
            imageUrl: exerciseImage("Mountain_Climbers"),
            equipment: ["Bodyweight"],
            instructions: ["Drive the knees under the body from a strong plank position.", "Keep shoulders stacked over hands and alternate legs quickly."],
          },
          sets: 6,
          reps: null,
          durationSeconds: 20,
          restSeconds: 40,
          tempo: "Hard / recover",
          coachingNote: "Fast legs, quiet hips. If form falls apart, slow it slightly.",
          coachingCues: ["Snap back to guard", "Feet under hips", "Exhale on every burst"],
          boxingRelevance: "Builds conditioning while forcing trunk stiffness, shoulder tolerance and hip speed.",
        },
      ],
    },
  ],
};
