import type { WorkoutDisplay } from "./types";

const IMAGE_BASE = "https://rabudzkpputmollmpodd.supabase.co/storage/v1/object/public/exercise-images";
const exerciseImage = (path: string) => `${IMAGE_BASE}/${path}/0.jpg`;

export const mockWorkout: WorkoutDisplay = {
  id: "demo-boxing-engine",
  title: "Boxing Engine: Legs, Core and Shoulder Armour",
  goal: "Build a repeatable conditioning base that carries into longer boxing rounds without turning the session into random gym punishment.",
  durationMinutes: 42,
  difficulty: "Intermediate",
  equipment: ["Dumbbells", "Resistance band", "Skipping rope", "Bodyweight"],
  visibility: "private",
  intakeSummary:
    "Generated from an intake asking for boxing-specific conditioning, shoulder resilience, explosive legs and enough core work to keep shape under fatigue.",
  createdAt: new Date("2026-05-05T06:00:00.000Z").toISOString(),
  sections: [
    {
      type: "warmup",
      title: "Warm up the engine",
      eyebrow: "Warmup",
      description: "Raise temperature, open the hips and switch on rotation before the harder work starts.",
      items: [
        {
          id: "mock-skip",
          orderIndex: 1,
          blockType: "warmup",
          blockTitle: "Warm up the engine",
          exercise: {
            id: "jump-rope",
            name: "Skip rope rhythm rounds",
            category: "conditioning",
            imageUrl: exerciseImage("Battling_Ropes"),
            equipment: ["Skipping rope"],
            instructions: ["Stay light on the balls of the feet.", "Keep shoulders loose and breathing steady."],
          },
          sets: 3,
          reps: null,
          durationSeconds: 60,
          restSeconds: 20,
          tempo: "Easy bounce",
          coachingNote: "Do not turn this into a max effort test. Grease the rhythm.",
          coachingCues: ["Tall posture", "Quiet feet", "Breathe through the nose where possible"],
          boxingRelevance: "Foot rhythm and relaxed shoulders are the base layer for clean boxing movement.",
        },
        {
          id: "mock-worlds-greatest",
          orderIndex: 2,
          blockType: "warmup",
          blockTitle: "Warm up the engine",
          exercise: {
            id: "worlds-greatest-stretch",
            name: "World's greatest stretch with rotation",
            category: "mobility",
            imageUrl: exerciseImage("All_Fours_Quad_Stretch"),
            equipment: ["Bodyweight"],
            instructions: ["Step into a deep lunge.", "Rotate through the upper back without collapsing the front knee."],
          },
          sets: 2,
          reps: "5 each side",
          durationSeconds: null,
          restSeconds: 15,
          tempo: "Controlled",
          coachingNote: "Own the end range. No flopping about like a wet towel.",
          coachingCues: ["Long spine", "Front foot rooted", "Rotate from ribs"],
          boxingRelevance: "Better hip and rib rotation gives punches somewhere to come from.",
        },
      ],
    },
    {
      type: "main",
      title: "Strength circuit",
      eyebrow: "Main work",
      description: "Alternating legs, pull and trunk so the session builds boxing durability without frying one joint pattern.",
      items: [
        {
          id: "mock-goblet-squat",
          orderIndex: 3,
          blockType: "main",
          blockTitle: "Strength circuit",
          exercise: {
            id: "goblet-squat",
            name: "Goblet squat",
            category: "strength",
            imageUrl: exerciseImage("Bodyweight_Squat"),
            equipment: ["Dumbbell"],
            instructions: ["Hold the dumbbell tight to the chest.", "Sit between the hips, drive the floor away."],
          },
          sets: 4,
          reps: "8-10",
          durationSeconds: null,
          restSeconds: 45,
          tempo: "3-1-1",
          coachingNote: "Make the last two reps hard without losing foot pressure.",
          coachingCues: ["Tripod foot", "Knees track toes", "Ribs stacked over pelvis"],
          boxingRelevance: "Leg strength keeps stance and shot quality alive when rounds get ugly.",
        },
        {
          id: "mock-band-row",
          orderIndex: 4,
          blockType: "main",
          blockTitle: "Strength circuit",
          exercise: {
            id: "band-row",
            name: "Band row with scap squeeze",
            category: "strength",
            imageUrl: exerciseImage("Alternating_Renegade_Row"),
            equipment: ["Resistance band"],
            instructions: ["Anchor the band at chest height.", "Pull elbows back and pause with shoulder blades together."],
          },
          sets: 4,
          reps: "12-15",
          durationSeconds: null,
          restSeconds: 30,
          tempo: "2-1-2",
          coachingNote: "Think posture and shoulder armour, not ego rowing.",
          coachingCues: ["Neck long", "Elbows finish behind ribs", "No shrugging"],
          boxingRelevance: "Stronger upper back helps your guard, posture and shoulder health survive volume.",
        },
        {
          id: "mock-deadbug",
          orderIndex: 5,
          blockType: "main",
          blockTitle: "Strength circuit",
          exercise: {
            id: "dead-bug",
            name: "Dead bug reach",
            category: "core",
            imageUrl: exerciseImage("Dead_Bug"),
            equipment: ["Bodyweight"],
            instructions: ["Press lower back gently into the floor.", "Reach opposite arm and leg without ribs flaring."],
          },
          sets: 4,
          reps: "8 each side",
          durationSeconds: null,
          restSeconds: 30,
          tempo: "Slow",
          coachingNote: "If your back arches, the rep does not count. Tragic, but fair.",
          coachingCues: ["Exhale hard", "Ribs down", "Move slow enough to own it"],
          boxingRelevance: "Anti-extension control protects shape when punching, slipping and bracing under fatigue.",
        },
      ],
    },
    {
      type: "finisher",
      title: "Round five finisher",
      eyebrow: "Finisher",
      description: "A short punchy close that feels like late-round pressure without needing a heavy bag.",
      items: [
        {
          id: "mock-shadow-sprint",
          orderIndex: 6,
          blockType: "finisher",
          blockTitle: "Round five finisher",
          exercise: {
            id: "shadowboxing-sprint",
            name: "Shadowboxing sprint intervals",
            category: "conditioning",
            imageUrl: exerciseImage("Mountain_Climbers"),
            equipment: ["Bodyweight"],
            instructions: ["Throw straight punches at high speed.", "Reset stance every time the feet get messy."],
          },
          sets: 6,
          reps: null,
          durationSeconds: 20,
          restSeconds: 40,
          tempo: "Hard / recover",
          coachingNote: "Fast hands, calm face. Panic is not a training method.",
          coachingCues: ["Snap back to guard", "Feet under hips", "Exhale on every burst"],
          boxingRelevance: "Practises staying technically organised when your lungs start negotiating surrender.",
        },
      ],
    },
  ],
};
